// SHARP Memory Display 2.7" 400x240px with Seeed Xiao ESP32S3
// this is the same display as used inside the Playdate game console from Panic (https://play.date/)
// created by upir, 2026
// youtube channel: https://www.youtube.com/upir_upir

// Youtube Video: https://youtu.be/LOICNiwDKaE
// Source Files: https://github.com/upiir/sharp_memory_display_xiao_esp32s3/

// Links related to this project:
// Do you like this video? You can buy me a coffee ☕: https://www.buymeacoffee.com/upir
// Xiao ESP32S3: https://s.click.aliexpress.com/e/_c3FqnKGj
// Xiao expansion board: https://s.click.aliexpress.com/e/_c4lpRFKF
// Jumper Wires: https://s.click.aliexpress.com/e/_c3Fh3hB9
// Playdate game console: https://play.date/
// Adafruit SHARP Memory Display Breakout // 2.7" 400x240: https://www.adafruit.com/product/4694
// SHARP Memory Display on Pimoroni: https://shop.pimoroni.com/products/adafruit-sharp-memory-display-breakout-2-7-400x240-monochrome
// Display documentation: https://learn.adafruit.com/adafruit-sharp-memory-display-breakout
// MacOS emulators: https://aresluna.org/frame-of-preference/
// Classic MacOS patterns: https://paulsmith.github.io/classic-mac-patterns/
// Xiao ESP32S3 documentation: https://wiki.seeedstudio.com/xiao_esp32s3_getting_started/
// Display connection: https://learn.adafruit.com/adafruit-sharp-memory-display-breakout/wiring
// Maclock: https://s.click.aliexpress.com/e/_c3XVbWMF
// Photopea (online graphics editor like Photoshop): https://www.photopea.com/

// Related videos with character displays:
// reTerminal eink displays: https://youtu.be/PtaXK2MAQ08
// 7-Segment LCD Display: https://youtu.be/BuPAdIORbwU
// Reflective LCD: https://youtu.be/ADmfI2H1qME
// Eink-like displays: https://youtu.be/jz01j1TpM84
// Eink YouTube Counter: https://youtu.be/HFFhTrAkerU
// LCD display: https://youtu.be/8V2kQTOjFhE


#include <Adafruit_GFX.h> // library for drawing
#include <Adafruit_SharpMem.h> // library for memory display

#include "images.h" // images.h is a separate file that has all the images generated by image2cpp website

// Xiao ESP32S3 --> Sharp Memory Display
// D0 -> SCK (Serial Clock) / CLK
// D1 -> MOSI (Maste out slave in)  / DI (Data In)
// D2 -> SS (Slave select) / CS (Chip Select) 
// GND -> GND (Ground)
// 3.3V -> 3.3V (Power)

#define SHARP_SCK  D0
#define SHARP_MOSI D1
#define SHARP_SS   D2

//                                                                      
//                            ┌─────────────┐                           
//                     ┌──────│     USB     │──────┐                    
//                     │      │             │      │                    
//                   ┌─┴─┐    │             │    ┌─┴─┐                  
//        CLK (Clock)│  O│ D0 │             │ 5V │O  │                  
//                   ├───┤    │             │    ├───┤                  
//       DI (Data In)│  O│ D1 └─────────────┘GND │O  │GND (Ground)      
//                   ├───┤                       ├───┤                  
//   CS (Chip Select)│  O│ D2                3V3 │O  │3.3V (Power)      
//                   ├───┤                       ├───┤                  
//                   │  O│ D3                D10 │O  │                  
//                   ├───┤                       ├───┤                  
//                   │  O│ D4                 D9 │O  │                  
//                   ├───┤                       ├───┤                  
//                   │  O│ D5                 D8 │O  │                  
//                   ├───┤                       ├───┤                  
//                   │  O│ D5                 D7 │O  │                  
//                   └─┬─┘                       └─┬─┘                  
//                     │ Seeed Studio Xiao ESP32S3 │                    
//                     └───────────────────────────┘                    
//                                                                      




Adafruit_SharpMem display(/* clock pin */ SHARP_SCK, /* data pin */ SHARP_MOSI, /* chip select pin */ SHARP_SS, /*width*/ 400, /*height*/ 240);

#define BLACK 0
#define WHITE 1


void setup(void)
{
  // start & clear the display
  display.begin();
  display.clearDisplay();
}

int i = 0; // counter to store the currently displayed image

void loop(void) {

   display.clearDisplay(); // clear the display (bitmaps are drawn "transparent")
   display.drawBitmap(/* x*/ 0, /* y */ 0, /* bitmap */ epd_bitmap_allArray[i] , /* w */ 400, /* h */ 240, /* color */ BLACK); // draw the image
   display.refresh(); // send the buffer to the display

   delay(2000); // wait 2 seconds
 
   // increment the counter
   i++;
   if (i > 7) {i = 0;}

}
